#!/usr/bin/env python3.6

def gather_info():
    height = float(input("What is your height in meters or inches? "))
    weight = float(input("What is your weight in pounds or kilos? "))
    system = input("Are your measurements in metric or imperial? ").lower().strip()
    return (height,weight,system)

def calculate_bmi(weight,height,system='metric'):
    if system == 'metric':
        bmi = (weight/(height**2))
    else:
        bmi = 703*(weight/(height**2))
    return bmi

while True:
    height,weight,system = gather_info()
    if system.startswith('i'):
        bmi = calculate_bmi(weight, system= 'imperial', height=height)
        print(f"Your BMI is {bmi}")
        break
    elif system.startswith('m'):
        bmi = calculate_bmi(weight,height)
        print(f" Your BMI is {bmi}")
        break
    else:
        print("Error: unknown measurement system. Please imperial or metric")

