#!/usr/bin/env python3.6

#Write a script that prompts the user for:

#A file_name where it should write the content.
#The content that should go in the file. The script should keep accepting lines of text until the user enters an empty line.
#After the user enters an empty line, write all of the lines to the file and end the script.

def get_filename(reprompt=False):
    if reprompt:
        print("Please enter a file name:")
    filename = input("Destination of file name :").strip()
    return filename or get_filename(true)

filename = get_filename()

print(f"Please enter the content of file. Entering a empty line will write content to file {filename}:\n")

with open (filename,'w') as f:
    eof = False
    lines = []

    while not eof:
        line = input()
        if line.strip():
            lines.append(f"{line}\n")

        else:
            eof = True
    f.writelines(lines)
    print(f"Lines written to file {filename}")

