#!/usr/bin/env python3.6

message = input(" Enter a message: ")
count = input(" Enter number of repeats: ").strip()

if count:
    count = int(count)
else:
    count = 1

def message_echo(message,count):
    while count > 0:
        print(message)
        count -= 1
message_echo(message,count)

