#!/usr/bin/env python3.6

import os
import requests
import sys

from argparse import ArgumentParser

parser = ArgumentParser(description ='Get the current weather information for your postcode')
parser.add_argument('zip',type=int, help='zip postal code to get wweather')
parser.add_argument('--country',default='us',help='country name')

args = parser.parse_args()

api_key = os.getenv("OWM_API_KEY")

if not api_key:
    print("Error: no api key found/set")
    sys.exit(1)
url = f"http://api.openweathermap.org/data/2.5/weather?zip={args.zip},{args.country}&appid={api_key}"

res = requests.get(url)

if res.status_code != 200:
    print(f" Error talking to weather provider: {res.status_code}")
    sys.exit(1)

print(res.json())

